"""Discord webhook notifications with rich embeds."""

import os

from discord_webhook import DiscordEmbed, DiscordWebhook

from .picker import PlayerRecommendation


def _get_trend_emoji(direction: str) -> str:
    """Get trend emoji."""
    if direction == "hot":
        return "🔥"
    elif direction == "cold":
        return "❄️"
    return ""


def _get_risk_emoji(dnp_risk: float) -> str:
    """Get risk emoji."""
    if dnp_risk >= 1.0:
        return "🚫"
    elif dnp_risk >= 0.5:
        return "⛔"
    elif dnp_risk > 0:
        return "⚠️"
    return ""


def _get_matchup_emoji(defense_factor: float, defender_factor: float) -> str:
    """Get matchup quality emoji."""
    combined = defense_factor * defender_factor
    if combined >= 1.10:
        return "🟢"
    elif combined >= 1.0:
        return "🟡"
    elif combined >= 0.90:
        return "🟠"
    else:
        return "🔴"


def _format_compact_pick(rank: int, rec: PlayerRecommendation) -> str:
    """Format a pick as a compact single line."""
    trend = _get_trend_emoji(rec.trend_direction)
    risk = _get_risk_emoji(rec.dnp_risk)
    matchup = _get_matchup_emoji(rec.defense_factor, rec.defender_factor)

    return f"`{rank:>2}.` **{rec.adjusted_score:>4.0f}** {rec.name} ({rec.team} vs {rec.opponent_team}) {matchup}{trend}{risk}"


def _format_detailed_pick(rank: int, rec: PlayerRecommendation) -> str:
    """Format a pick with detailed analysis."""
    matchup = _get_matchup_emoji(rec.defense_factor, rec.defender_factor)

    # Build matchup text
    matchup_text = f"{matchup} "
    if rec.defense_factor >= 1.08:
        matchup_text += "Weak defense"
    elif rec.defense_factor <= 0.92:
        matchup_text += "Tough defense"
    else:
        matchup_text += "Average defense"

    if rec.best_defender and rec.defender_factor < 0.95:
        matchup_text += f" (vs {rec.best_defender})"

    # Build status text
    if rec.dnp_risk >= 1.0:
        status = "🚫 OUT"
    elif rec.dnp_risk >= 0.5:
        status = f"⛔ {rec.injury_status} ({int(rec.dnp_risk*100)}%)"
    elif rec.dnp_risk > 0:
        status = f"⚠️ {rec.injury_status} ({int(rec.dnp_risk*100)}%)"
    else:
        status = "✅ Healthy"

    # Build trend text
    if rec.trend_direction == "hot":
        trend_text = f"🔥 {rec.trend_display}"
    elif rec.trend_direction == "cold":
        trend_text = f"❄️ {rec.trend_display}"
    else:
        trend_text = "➡️ Stable"

    return (
        f"**#{rank} {rec.name}** ({rec.team} vs {rec.opponent_team})\n"
        f"Score: **{rec.adjusted_score:.1f}** | Avg: {rec.avg_ttfl:.1f} | {trend_text}\n"
        f"{matchup_text}\n"
        f"{status}"
    )


def _generate_full_rankings_file(recommendations: list[PlayerRecommendation], date: str) -> str:
    """Generate full top 50 rankings as formatted text."""
    lines = [
        f"TTFL Rankings - {date}",
        "=" * 60,
        "",
        f"{'#':>3}  {'Score':>5}  {'Player':<22} {'Team':>4} {'vs':>4}  {'Avg':>5}  {'Trend':>6}  Status",
        "-" * 80,
    ]

    for i, rec in enumerate(recommendations[:50], 1):
        # Trend indicator
        if rec.trend_direction == "hot":
            trend = f"+{int((rec.trend_factor - 1) * 100)}%"
        elif rec.trend_direction == "cold":
            trend = f"{int((rec.trend_factor - 1) * 100)}%"
        else:
            trend = "stable"

        # Status
        if rec.dnp_risk >= 1.0:
            status = "OUT"
        elif rec.dnp_risk >= 0.5:
            status = f"{rec.injury_status} ({int(rec.dnp_risk*100)}%)"
        elif rec.dnp_risk > 0:
            status = f"{rec.injury_status} ({int(rec.dnp_risk*100)}%)"
        else:
            status = "OK"

        # Matchup indicator
        combined = rec.defense_factor * rec.defender_factor
        if combined >= 1.10:
            matchup = "[+]"
        elif combined >= 1.0:
            matchup = "[ ]"
        elif combined >= 0.90:
            matchup = "[-]"
        else:
            matchup = "[!]"

        line = f"{i:>3}  {rec.adjusted_score:>5.1f}  {rec.name:<22} {rec.team:>4} {rec.opponent_team:>4}  {rec.avg_ttfl:>5.1f}  {trend:>6}  {matchup} {status}"
        lines.append(line)

    lines.extend([
        "",
        "-" * 80,
        "Legend:",
        "  Score = Risk-adjusted expected TTFL score",
        "  Avg   = Simple average from last 10 games",
        "  Trend = Hot/cold streak adjustment",
        "  [+] Great matchup | [ ] Neutral | [-] Tough | [!] Very tough",
        "",
        "Generated by TTFL Picker",
    ])

    return "\n".join(lines)


def _build_top_picks_embed(recommendations: list[PlayerRecommendation], date: str) -> DiscordEmbed:
    """Build compact embed for top 10 obvious picks."""
    embed = DiscordEmbed(
        title=f"🏀 TTFL {date} - Top Picks",
        description="*Pick these if you haven't already*",
        color="2ecc71",  # Green
    )

    # Split into two columns
    top_10 = recommendations[:10]
    left = "\n".join(_format_compact_pick(i, r) for i, r in enumerate(top_10[:5], 1))
    right = "\n".join(_format_compact_pick(i, r) for i, r in enumerate(top_10[5:10], 6))

    embed.add_embed_field(name="1-5", value=left or "—", inline=True)
    embed.add_embed_field(name="6-10", value=right or "—", inline=True)

    # Add legend
    embed.add_embed_field(
        name="",
        value="🟢 Great | 🟡 Neutral | 🟠 Tough | 🔴 Hard | 🔥 Hot | ❄️ Cold | ⚠️ Injury",
        inline=False,
    )

    return embed


def _build_value_picks_embed(recommendations: list[PlayerRecommendation]) -> DiscordEmbed | None:
    """Build detailed embed for value picks (11-25)."""
    value_picks = [r for r in recommendations[10:25] if r.dnp_risk < 1.0]

    if not value_picks:
        return None

    embed = DiscordEmbed(
        title="💎 Value Picks (#11-25)",
        description="*Deep cuts for when stars are locked*",
        color="3498db",  # Blue
    )

    # Show top 4 value picks with full details
    for i, rec in enumerate(value_picks[:4], 11):
        embed.add_embed_field(
            name="",
            value=_format_detailed_pick(i, rec),
            inline=False,
        )

    return embed


def post_to_discord(
    recommendations: list[PlayerRecommendation],
    date: str,
    webhook_url: str | None = None,
) -> bool:
    """Post recommendations to Discord with rich embeds + full rankings file.

    Structure:
    1. Top 10 picks (compact) - "pick if available"
    2. Value picks #11-25 (detailed) - the real insights
    3. Attached file with full top 50 rankings

    Args:
        recommendations: List of player recommendations
        date: Date string (YYYY-MM-DD)
        webhook_url: Optional webhook URL (defaults to DISCORD_WEBHOOK_URL env var)

    Returns:
        True if posting succeeded, False otherwise

    Raises:
        ValueError: If no webhook URL is configured
    """
    url = webhook_url or os.getenv("DISCORD_WEBHOOK_URL") or os.getenv("DISCORD_TTFL")
    if not url:
        raise ValueError("DISCORD_WEBHOOK_URL or DISCORD_TTFL not set in .env")

    if not recommendations:
        return False

    webhook = DiscordWebhook(url=url, username="TTFL Picker", rate_limit_retry=True)

    # Top picks embed
    top_embed = _build_top_picks_embed(recommendations, date)
    top_embed.set_timestamp()
    webhook.add_embed(top_embed)

    # Value picks embed
    if len(recommendations) > 10:
        value_embed = _build_value_picks_embed(recommendations)
        if value_embed:
            value_embed.set_footer(text="📎 Full top 50 rankings attached below")
            webhook.add_embed(value_embed)

    # Generate and attach full rankings file
    if len(recommendations) > 10:
        rankings_text = _generate_full_rankings_file(recommendations, date)
        webhook.add_file(file=rankings_text.encode('utf-8'), filename=f"ttfl-rankings-{date}.txt")

    response = webhook.execute()

    return response.status_code == 200
